# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: blog.teemu.im
email: teemu.harju@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Teemu and this is my Weblog.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.teemu.im" # the base hostname & protocol for your site
twitter_username: tsharju
github_username:  tsharju
permalink: /:year/:month/:day/:title/
encoding: utf-8
timezone: Europe/Helsinki

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman